const mongoose = require('mongoose');
const dotenv = require('dotenv');

dotenv.config();

const User = require('./models/User');
const Product = require('./models/Product');
const Category = require('./models/Category');
const Brand = require('./models/Brand');
const Order = require('./models/Order');
const Coupon = require('./models/Coupon');
const Review = require('./models/Review');
const Banner = require('./models/Banner');
const Settings = require('./models/Settings');

const connectDB = require('./config/database');

const seed = async () => {
  try {
    await connectDB();

    await Promise.all([
      User.deleteMany({}),
      Product.deleteMany({}),
      Category.deleteMany({}),
      Brand.deleteMany({}),
      Order.deleteMany({}),
      Coupon.deleteMany({}),
      Review.deleteMany({}),
      Banner.deleteMany({}),
      Settings.deleteMany({}),
    ]);

    console.log('Cleared existing data...');

    // Create Users
    const password = 'Test@1234';

    const users = await User.create([
      {
        name: 'Admin User',
        email: 'admin@luxuryperfume.com',
        password,
        role: 'admin',
        isVerified: true,
        phone: '+92-300-1111111',
        addresses: [{ name: 'Admin', phone: '+92-300-1111111', street: '1 Mall Road', city: 'Lahore', state: 'Punjab', zip: '54000', country: 'Pakistan', isDefault: true }],
      },
      {
        name: 'Manager User',
        email: 'manager@luxuryperfume.com',
        password,
        role: 'admin',
        isVerified: true,
        phone: '+92-300-2222222',
        addresses: [{ name: 'Manager', phone: '+92-300-2222222', street: '10 Clifton Road', city: 'Karachi', state: 'Sindh', zip: '75600', country: 'Pakistan', isDefault: true }],
      },
      {
        name: 'Sarah Khan',
        email: 'sarah@example.com',
        password,
        role: 'customer',
        isVerified: true,
        phone: '+92-300-3333333',
        addresses: [{ name: 'Sarah Khan', phone: '+92-300-3333333', street: '25 F-7 Markaz', city: 'Islamabad', state: 'ICT', zip: '44000', country: 'Pakistan', isDefault: true }],
      },
      {
        name: 'Ahmed Ali',
        email: 'james@example.com',
        password,
        role: 'customer',
        isVerified: true,
        phone: '+92-300-4444444',
        addresses: [{ name: 'Ahmed Ali', phone: '+92-300-4444444', street: '55 Gulberg III', city: 'Lahore', state: 'Punjab', zip: '54660', country: 'Pakistan', isDefault: true }],
      },
      {
        name: 'Fatima Zaidi',
        email: 'emily@example.com',
        password,
        role: 'customer',
        isVerified: false,
        phone: '+92-300-5555555',
        addresses: [{ name: 'Fatima Zaidi', phone: '+92-300-5555555', street: '8 University Road', city: 'Karachi', state: 'Sindh', zip: '75270', country: 'Pakistan', isDefault: true }],
      },
    ]);

    console.log('Users created...');

    // Create Categories
    const categories = await Category.create([
      { name: 'Floral', description: 'Captivating fragrances built around flower notes including rose, jasmine, lavender, and violet.', isActive: true },
      { name: 'Oriental', description: 'Warm, sensual scents featuring exotic spices, amber, vanilla, and precious resins.', isActive: true },
      { name: 'Woody', description: 'Sophisticated compositions centered on cedar, sandalwood, patchouli, and vetiver.', isActive: true },
      { name: 'Fresh', description: 'Clean, invigorating fragrances with citrus, aquatic, and green notes.', isActive: true },
      { name: 'Citrus', description: 'Bright, zesty perfumes dominated by lemon, bergamot, orange, and grapefruit notes.', isActive: true },
      { name: 'Gourmand', description: 'Deliciously edible scents with notes of vanilla, chocolate, caramel, and coffee.', isActive: true },
      { name: 'Aquatic', description: 'Fresh, marine-inspired fragrances evoking the ocean breeze and sea spray.', isActive: true },
      { name: 'Green', description: 'Crisp, natural scents inspired by fresh-cut grass, leaves, and woodland foliage.', isActive: true },
    ]);

    console.log('Categories created...');

    // Create Brands
    const brands = await Brand.create([
      { name: 'Tom Ford', description: 'Luxury American fashion house known for bold, sensual fragrances with exceptional longevity.', logo: 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=200&h=200&fit=crop', isActive: true },
      { name: 'Dior', description: 'Iconic French fashion house creating timeless, elegant perfumes since 1947.', logo: 'https://images.unsplash.com/photo-1587017539504-67cfbddac569?w=200&h=200&fit=crop', isActive: true },
      { name: 'Chanel', description: 'Legendary French fashion house, home to the iconic Chanel No. 5.', logo: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=200&h=200&fit=crop', isActive: true },
      { name: 'Creed', description: 'Premium British perfume house established in 1760, known for hand-crafted luxury fragrances.', logo: 'https://images.unsplash.com/photo-1563170351-be82bc888aa4?w=200&h=200&fit=crop', isActive: true },
      { name: 'Le Labo', description: 'Artisanal New York-based fragrance brand creating hand-blended, minimalist scents.', logo: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=200&h=200&fit=crop', isActive: true },
      { name: 'Jo Malone', description: 'British fragrance house renowned for elegant, layered scents and cologne collections.', logo: 'https://images.unsplash.com/photo-1600612253971-422e7f7faeb6?w=200&h=200&fit=crop', isActive: true },
      { name: 'Byredo', description: 'Swedish contemporary luxury brand creating modern, minimalist fragrances with distinctive character.', logo: 'https://images.unsplash.com/photo-1551103782-8ab07afd45c1?w=200&h=200&fit=crop', isActive: true },
      { name: 'Maison Margiela', description: 'Avant-garde French fashion house with the Replica fragrance collection evoking memories.', logo: 'https://images.unsplash.com/photo-1522512115668-c09775d6f424?w=200&h=200&fit=crop', isActive: true },
      { name: 'Kilian', description: 'Luxury French fragrance house creating opulent, sophisticated scents with lasting power.', logo: 'https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=200&h=200&fit=crop', isActive: true },
      { name: 'Diptyque', description: 'Parisian perfumery known for artistic, poetic fragrances inspired by travel and nature.', logo: 'https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=200&h=200&fit=crop', isActive: true },
    ]);

    console.log('Brands created...');

    // Create Products
    const products = await Product.create([
      {
        name: 'Black Orchid Eau de Parfum',
        description: 'A luxurious, modern classic that opens with rich black truffle and ylang-ylang, blooming into a heart of black orchid and lotus wood. The sensual base of patchouli, sandalwood, and amber creates an unforgettable signature scent that lasts all day.',
        shortDescription: 'An opulent blend of black truffle, ylang-ylang, and black orchid with a sensual woody base.',
        images: ['https://images.unsplash.com/photo-1541643600914-78b084683601?w=640&h=640&fit=crop'],
        category: categories[1]._id,
        brand: brands[0]._id,
        price: 19500,
        discount: 10,
        sizes: [
          { size: '30ml', price: 9500, stock: 50, sku: 'TF-BO-30' },
          { size: '50ml', price: 15500, stock: 80, sku: 'TF-BO-50' },
          { size: '100ml', price: 19500, stock: 120, sku: 'TF-BO-100' },
        ],
        concentration: 'EDP',
        topNotes: ['Black Truffle', 'Ylang-Ylang', 'Bergamot'],
        middleNotes: ['Black Orchid', 'Lotus Wood', 'Fruit Notes'],
        baseNotes: ['Patchouli', 'Sandalwood', 'Amber', 'Vanilla', 'Incense'],
        longevity: 'Excellent',
        projection: 'Very Good',
        sillage: 'Excellent',
        season: 'Fall',
        occasion: 'Evening',
        gender: 'unisex',
        tags: ['luxury', 'oriental', 'evening', 'sensual', 'best-seller'],
        isFeatured: true,
        isTrending: true,
        isBestSeller: true,
        isNewArrival: false,
        isLimitedEdition: false,
        isVisible: true,
        stock: 120,
        lowStockThreshold: 10,
      },
      {
        name: 'Sauvage Elixir',
        description: 'An intensely aromatic and powerful fragrance crafted by master perfumer François Demachy. A radical elixir with notes of cinnamon, nutmeg, and lavender that creates an exceptionally concentrated and long-lasting scent experience.',
        shortDescription: 'An intensely aromatic elixir with cinnamon, nutmeg, and lavender in a radical concentration.',
        images: ['https://images.unsplash.com/photo-1587017539504-67cfbddac569?w=640&h=640&fit=crop'],
        category: categories[3]._id,
        brand: brands[1]._id,
        price: 18500,
        sizes: [
          { size: '30ml', price: 9500, stock: 40, sku: 'DR-SE-30' },
          { size: '60ml', price: 14500, stock: 60, sku: 'DR-SE-60' },
          { size: '100ml', price: 18500, stock: 100, sku: 'DR-SE-100' },
        ],
        concentration: 'Parfum',
        topNotes: ['Cinnamon', 'Nutmeg', 'Grapefruit'],
        middleNotes: ['Lavender', 'Star Anise', 'Cardamom'],
        baseNotes: ['Amber', 'Sandalwood', 'Patchouli', 'Licorice'],
        longevity: 'Excellent',
        projection: 'Excellent',
        sillage: 'Excellent',
        season: 'Winter',
        occasion: 'Formal',
        gender: 'male',
        tags: ['masculine', 'intense', 'long-lasting', 'luxury'],
        isFeatured: true,
        isTrending: true,
        isBestSeller: true,
        isNewArrival: false,
        isLimitedEdition: false,
        isVisible: true,
        stock: 100,
        lowStockThreshold: 10,
      },
      {
        name: 'Chanel No. 5 Eau de Parfum',
        description: 'The timeless icon of perfumery. Created in 1921 by Ernest Beaux, this legendary floral-aldehyde fragrance features an abstract composition of jasmine, rose, and ylang-ylang that has captivated women for generations.',
        shortDescription: 'The legendary floral-aldehyde fragrance that defined modern perfumery.',
        images: ['https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=640&h=640&fit=crop'],
        category: categories[0]._id,
        brand: brands[2]._id,
        price: 16500,
        sizes: [
          { size: '35ml', price: 9500, stock: 60, sku: 'CH-N5-35' },
          { size: '50ml', price: 13500, stock: 90, sku: 'CH-N5-50' },
          { size: '100ml', price: 16500, stock: 110, sku: 'CH-N5-100' },
        ],
        concentration: 'EDP',
        topNotes: ['Aldehydes', 'Ylang-Ylang', 'Neroli', 'Bergamot'],
        middleNotes: ['Jasmine', 'Rose', 'Iris', 'Lily of the Valley'],
        baseNotes: ['Amber', 'Sandalwood', 'Vanilla', 'Musk', 'Vetiver'],
        longevity: 'Very Good',
        projection: 'Moderate',
        sillage: 'Good',
        season: 'All Seasons',
        occasion: 'Special Occasion',
        gender: 'female',
        tags: ['iconic', 'floral', 'timeless', 'luxury', 'classic'],
        isFeatured: true,
        isTrending: false,
        isBestSeller: true,
        isNewArrival: false,
        isLimitedEdition: false,
        isVisible: true,
        stock: 110,
        lowStockThreshold: 10,
      },
      {
        name: 'Aventus',
        description: 'The undisputed modern masterpiece from Creed. A bold, sophisticated fragrance that celebrates power, strength, and success. Opening with pineapple and blackcurrant, developing into a heart of birch and jasmine, resting on a base of musk and oakmoss.',
        shortDescription: 'The iconic modern masterpiece featuring pineapple, birch, and musk.',
        images: ['https://images.unsplash.com/photo-1563170351-be82bc888aa4?w=640&h=640&fit=crop'],
        category: categories[3]._id,
        brand: brands[3]._id,
        price: 43500,
        sizes: [
          { size: '50ml', price: 29500, stock: 30, sku: 'CR-AV-50' },
          { size: '100ml', price: 43500, stock: 50, sku: 'CR-AV-100' },
          { size: '250ml', price: 85000, stock: 15, sku: 'CR-AV-250' },
        ],
        concentration: 'EDP',
        topNotes: ['Pineapple', 'Blackcurrant', 'Bergamot', 'Apple'],
        middleNotes: ['Birch', 'Jasmine', 'Rose', 'Patchouli'],
        baseNotes: ['Musk', 'Oakmoss', 'Ambergris', 'Vanilla'],
        longevity: 'Very Good',
        projection: 'Excellent',
        sillage: 'Very Good',
        season: 'Spring',
        occasion: 'Formal',
        gender: 'male',
        tags: ['iconic', 'premium', 'masculine', 'luxury', 'best-seller'],
        isFeatured: true,
        isTrending: true,
        isBestSeller: true,
        isNewArrival: false,
        isLimitedEdition: false,
        isVisible: true,
        stock: 50,
        lowStockThreshold: 5,
      },
      {
        name: 'Santal 33',
        description: 'An iconic, cult-favorite fragrance from Le Labo that transcends gender. The unmistakable scent of sandalwood wrapped in warm, spicy notes of cardamom, violet, and cedar. A true modern classic that has defined a generation of fragrance lovers.',
        shortDescription: 'The cult-favorite sandalwood fragrance with spicy cardamom and cedar notes.',
        images: ['https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=640&h=640&fit=crop'],
        category: categories[2]._id,
        brand: brands[4]._id,
        price: 29800,
        sizes: [
          { size: '15ml', price: 8500, stock: 70, sku: 'LL-S33-15' },
          { size: '50ml', price: 19800, stock: 100, sku: 'LL-S33-50' },
          { size: '100ml', price: 29800, stock: 80, sku: 'LL-S33-100' },
        ],
        concentration: 'EDP',
        topNotes: ['Cardamom', 'Violet', 'Pineapple'],
        middleNotes: ['Sandalwood', 'Cedar', 'Papyrus'],
        baseNotes: ['Leather', 'Musk', 'Amber', 'Iso E Super'],
        longevity: 'Very Good',
        projection: 'Good',
        sillage: 'Very Good',
        season: 'Fall',
        occasion: 'Everyday',
        gender: 'unisex',
        tags: ['cult', 'sandalwood', 'minimalist', 'unisex', 'trending'],
        isFeatured: true,
        isTrending: true,
        isBestSeller: true,
        isNewArrival: false,
        isLimitedEdition: false,
        isVisible: true,
        stock: 80,
        lowStockThreshold: 10,
      },
      {
        name: 'Wood Sage & Sea Salt',
        description: 'A walk along the windswept British coastline captured in a bottle. This invigorating, mineral fragrance combines the freshness of sea salt with the earthy warmth of sage and the woody depth of driftwood.',
        shortDescription: 'A refreshing, mineral fragrance evoking the windswept British coastline.',
        images: ['https://images.unsplash.com/photo-1600612253971-422e7f7faeb6?w=640&h=640&fit=crop'],
        category: categories[6]._id,
        brand: brands[5]._id,
        price: 14500,
        sizes: [
          { size: '30ml', price: 7000, stock: 100, sku: 'JM-WS-30' },
          { size: '100ml', price: 14500, stock: 150, sku: 'JM-WS-100' },
        ],
        concentration: 'Cologne',
        topNotes: ['Sea Salt', 'Grapefruit'],
        middleNotes: ['Sage', 'Ambrette', 'Seaweed'],
        baseNotes: ['Driftwood', 'Musk', 'Mineral Notes'],
        longevity: 'Moderate',
        projection: 'Moderate',
        sillage: 'Moderate',
        season: 'Summer',
        occasion: 'Casual',
        gender: 'unisex',
        tags: ['fresh', 'summer', 'coastal', 'unisex', 'light'],
        isFeatured: false,
        isTrending: true,
        isBestSeller: false,
        isNewArrival: false,
        isLimitedEdition: false,
        isVisible: true,
        stock: 150,
        lowStockThreshold: 15,
      },
      {
        name: 'Gypsy Water',
        description: 'Inspired by the Romani lifestyle, this captivating fragrance blends the warmth of vanilla and sandalwood with fresh notes of bergamot, lemon, and juniper berries. A mystical scent of forest floors and campfire smoke.',
        shortDescription: 'A mystical blend of bergamot, juniper, vanilla, and sandalwood inspired by nature.',
        images: ['https://images.unsplash.com/photo-1551103782-8ab07afd45c1?w=640&h=640&fit=crop'],
        category: categories[2]._id,
        brand: brands[6]._id,
        price: 29000,
        sizes: [
          { size: '50ml', price: 20000, stock: 60, sku: 'BY-GW-50' },
          { size: '100ml', price: 29000, stock: 90, sku: 'BY-GW-100' },
        ],
        concentration: 'EDP',
        topNotes: ['Bergamot', 'Lemon', 'Juniper Berries', 'Pink Pepper'],
        middleNotes: ['Incense', 'Pine Needles', 'Orris Root'],
        baseNotes: ['Vanilla', 'Sandalwood', 'Amber'],
        longevity: 'Good',
        projection: 'Moderate',
        sillage: 'Good',
        season: 'Spring',
        occasion: 'Everyday',
        gender: 'unisex',
        tags: ['woody', 'fresh', 'unisex', 'nature-inspired', 'trending'],
        isFeatured: true,
        isTrending: true,
        isBestSeller: false,
        isNewArrival: false,
        isLimitedEdition: false,
        isVisible: true,
        stock: 90,
        lowStockThreshold: 10,
      },
      {
        name: 'Jazz Club',
        description: 'A sensual, sophisticated scent that captures the atmosphere of a dimly lit jazz club. Rich notes of rum, tobacco leaf, and vanilla are wrapped in warm, spicy undertones of clary sage and styrax.',
        shortDescription: 'A warm, sensual blend of rum, tobacco, and vanilla in a sultry jazz club atmosphere.',
        images: ['https://images.unsplash.com/photo-1522512115668-c09775d6f424?w=640&h=640&fit=crop'],
        category: categories[1]._id,
        brand: brands[7]._id,
        price: 15000,
        sizes: [
          { size: '30ml', price: 7800, stock: 80, sku: 'MM-JC-30' },
          { size: '100ml', price: 15000, stock: 120, sku: 'MM-JC-100' },
        ],
        concentration: 'EDT',
        topNotes: ['Rum', 'Pink Pepper', 'Clary Sage'],
        middleNotes: ['Tobacco Leaf', 'Styrax', 'Geranium'],
        baseNotes: ['Vanilla', 'Tonka Bean', 'Leather'],
        longevity: 'Good',
        projection: 'Good',
        sillage: 'Good',
        season: 'Fall',
        occasion: 'Evening',
        gender: 'male',
        tags: ['warm', 'tobacco', 'rum', 'evening', 'masculine'],
        isFeatured: false,
        isTrending: true,
        isBestSeller: true,
        isNewArrival: false,
        isLimitedEdition: false,
        isVisible: true,
        stock: 120,
        lowStockThreshold: 10,
      },
      {
        name: 'Love Don\'t Be Shy',
        description: 'An intensely romantic and gourmand fragrance that opens with sparkling neroli and orange blossom, wrapped in a heart of rose, jasmine, and orris. The seductive base of marshmallow, vanilla, and musk creates an irresistible, addictive scent.',
        shortDescription: 'A romantic gourmand fragrance with neroli, orange blossom, and marshmallow.',
        images: ['https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=640&h=640&fit=crop'],
        category: categories[5]._id,
        brand: brands[8]._id,
        price: 29500,
        sizes: [
          { size: '50ml', price: 19500, stock: 40, sku: 'KL-LD-50' },
          { size: '100ml', price: 29500, stock: 70, sku: 'KL-LD-100' },
        ],
        concentration: 'EDP',
        topNotes: ['Neroli', 'Orange Blossom', 'Bergamot'],
        middleNotes: ['Rose', 'Jasmine', 'Orris', 'Coriander'],
        baseNotes: ['Marshmallow', 'Vanilla', 'Musk', 'Sugar'],
        longevity: 'Excellent',
        projection: 'Very Good',
        sillage: 'Very Good',
        season: 'Spring',
        occasion: 'Romantic',
        gender: 'female',
        tags: ['gourmand', 'romantic', 'sweet', 'luxury', 'feminine'],
        isFeatured: false,
        isTrending: true,
        isBestSeller: true,
        isNewArrival: false,
        isLimitedEdition: false,
        isVisible: true,
        stock: 70,
        lowStockThreshold: 10,
      },
      {
        name: 'Philosykos Eau de Parfum',
        description: 'A stunning tribute to the entire fig tree - leaves, fruit, and wood. This green, woody, and milky fragrance captures the essence of the Mediterranean with incredible realism. A masterful creation that transports you to a sun-drenched Greek grove.',
        shortDescription: 'A green, woody tribute to the fig tree capturing the essence of the Mediterranean.',
        images: ['https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=640&h=640&fit=crop'],
        category: categories[7]._id,
        brand: brands[9]._id,
        price: 21000,
        sizes: [
          { size: '50ml', price: 15000, stock: 55, sku: 'DP-PH-50' },
          { size: '100ml', price: 21000, stock: 85, sku: 'DP-PH-100' },
        ],
        concentration: 'EDP',
        topNotes: ['Fig Leaf', 'Fig Tree', 'Coconut'],
        middleNotes: ['Fig', 'Green Notes', 'Mulberry'],
        baseNotes: ['Cedar', 'Woodsy Notes', 'Milk'],
        longevity: 'Good',
        projection: 'Moderate',
        sillage: 'Good',
        season: 'Summer',
        occasion: 'Casual',
        gender: 'unisex',
        tags: ['green', 'fig', 'mediterranean', 'natural', 'unisex'],
        isFeatured: false,
        isTrending: false,
        isBestSeller: false,
        isNewArrival: false,
        isLimitedEdition: false,
        isVisible: true,
        stock: 85,
        lowStockThreshold: 10,
      },
      {
        name: 'Tobacco Vanille',
        description: 'A rich, opulent fragrance from Tom Ford\'s Private Blend. Sweet cream, vanilla, and tobacco leaf create a warm, comforting yet sophisticated scent. Accents of dried fruits and cocoa add depth to this cold-weather masterpiece.',
        shortDescription: 'A warm, opulent blend of tobacco leaf, vanilla, and cocoa from the Private Blend.',
        images: ['https://images.unsplash.com/photo-1541643600914-78b084683601?w=640&h=640&fit=crop'],
        category: categories[1]._id,
        brand: brands[0]._id,
        price: 29500,
        sizes: [
          { size: '50ml', price: 19500, stock: 45, sku: 'TF-TV-50' },
          { size: '100ml', price: 29500, stock: 75, sku: 'TF-TV-100' },
          { size: '250ml', price: 55000, stock: 20, sku: 'TF-TV-250' },
        ],
        concentration: 'EDP',
        topNotes: ['Tobacco Leaf', 'Spicy Notes'],
        middleNotes: ['Vanilla', 'Cocoa', 'Tonka Bean', 'Dried Fruits'],
        baseNotes: ['Cream', 'Woody Notes', 'Sweet Resins'],
        longevity: 'Excellent',
        projection: 'Very Good',
        sillage: 'Excellent',
        season: 'Winter',
        occasion: 'Evening',
        gender: 'male',
        tags: ['tobacco', 'vanilla', 'winter', 'luxury', 'private-blend'],
        isFeatured: true,
        isTrending: false,
        isBestSeller: true,
        isNewArrival: false,
        isLimitedEdition: false,
        isVisible: true,
        stock: 75,
        lowStockThreshold: 10,
      },
      {
        name: 'J\'adore Eau de Parfum',
        description: 'A luminous, feminine fragrance that celebrates the ultimate expression of womanhood. A magnificent floral bouquet of ylang-ylang, damask rose, and jasmine sambac, wrapped in a fresh top of pear and melon.',
        shortDescription: 'A luminous floral bouquet of ylang-ylang, rose, and jasmine sambac.',
        images: ['https://images.unsplash.com/photo-1587017539504-67cfbddac569?w=640&h=640&fit=crop'],
        category: categories[0]._id,
        brand: brands[1]._id,
        price: 14000,
        sizes: [
          { size: '30ml', price: 7200, stock: 80, sku: 'DR-JD-30' },
          { size: '50ml', price: 10800, stock: 110, sku: 'DR-JD-50' },
          { size: '100ml', price: 14000, stock: 130, sku: 'DR-JD-100' },
        ],
        concentration: 'EDP',
        topNotes: ['Pear', 'Melon', 'Peach', 'Bergamot'],
        middleNotes: ['Ylang-Ylang', 'Damask Rose', 'Jasmine Sambac', 'Lily of the Valley'],
        baseNotes: ['Cedar', 'Vanilla', 'Musk', 'Sandalwood'],
        longevity: 'Very Good',
        projection: 'Good',
        sillage: 'Very Good',
        season: 'Spring',
        occasion: 'Everyday',
        gender: 'female',
        tags: ['floral', 'feminine', 'elegant', 'luxury', 'classic'],
        isFeatured: false,
        isTrending: false,
        isBestSeller: true,
        isNewArrival: false,
        isLimitedEdition: false,
        isVisible: true,
        stock: 130,
        lowStockThreshold: 15,
      },
      {
        name: 'Bleu de Chanel Eau de Parfum',
        description: 'An iconic fragrance for the modern man who defies convention. An aromatic-woody composition with citrus and incense that creates a powerful, commanding presence. Fresh yet deep, classic yet innovative.',
        shortDescription: 'An iconic aromatic-woody fragrance with citrus and incense for the modern man.',
        images: ['https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=640&h=640&fit=crop'],
        category: categories[2]._id,
        brand: brands[2]._id,
        price: 15500,
        sizes: [
          { size: '50ml', price: 10500, stock: 90, sku: 'CH-BC-50' },
          { size: '100ml', price: 15500, stock: 140, sku: 'CH-BC-100' },
          { size: '150ml', price: 19500, stock: 50, sku: 'CH-BC-150' },
        ],
        concentration: 'EDP',
        topNotes: ['Grapefruit', 'Lemon', 'Mint', 'Pink Pepper'],
        middleNotes: ['Ginger', 'Nutmeg', 'Jasmine', 'Incense'],
        baseNotes: ['Cedar', 'Sandalwood', 'Amber', 'Musk', 'Patchouli'],
        longevity: 'Very Good',
        projection: 'Good',
        sillage: 'Very Good',
        season: 'All Seasons',
        occasion: 'Office',
        gender: 'male',
        tags: ['masculine', 'versatile', 'iconic', 'fresh', 'woody'],
        isFeatured: false,
        isTrending: false,
        isBestSeller: true,
        isNewArrival: false,
        isLimitedEdition: false,
        isVisible: true,
        stock: 140,
        lowStockThreshold: 15,
      },
      {
        name: 'Green Irish Tweed',
        description: 'Creed\'s legendary fresh green fragrance, a timeless masterpiece that epitomizes elegance. The sparkling top of lemon and verbena gives way to a heart of violet leaves and iris before settling into a refined base of sandalwood and ambergris.',
        shortDescription: 'The legendary fresh green masterpiece with lemon, violet, and sandalwood.',
        images: ['https://images.unsplash.com/photo-1563170351-be82bc888aa4?w=640&h=640&fit=crop'],
        category: categories[7]._id,
        brand: brands[3]._id,
        price: 39500,
        sizes: [
          { size: '50ml', price: 24500, stock: 25, sku: 'CR-GIT-50' },
          { size: '100ml', price: 39500, stock: 45, sku: 'CR-GIT-100' },
          { size: '250ml', price: 75000, stock: 10, sku: 'CR-GIT-250' },
        ],
        concentration: 'EDP',
        topNotes: ['Lemon', 'Verbena', 'Peppermint'],
        middleNotes: ['Violet Leaves', 'Iris', 'Sage'],
        baseNotes: ['Sandalwood', 'Ambergris', 'Cedar'],
        longevity: 'Good',
        projection: 'Good',
        sillage: 'Very Good',
        season: 'Spring',
        occasion: 'Formal',
        gender: 'male',
        tags: ['green', 'fresh', 'elegant', 'premium', 'classic'],
        isFeatured: false,
        isTrending: true,
        isBestSeller: true,
        isNewArrival: false,
        isLimitedEdition: false,
        isVisible: true,
        stock: 45,
        lowStockThreshold: 5,
      },
      {
        name: 'Another 13',
        description: 'An enigmatic, addictive fragrance from Le Labo that seems to smell different on everyone. Built around ambroxan, jasmine absolute, and moss, this minimalist masterpiece is both subtle and captivating - a true second skin scent.',
        shortDescription: 'An enigmatic minimalist fragrance with ambroxan, jasmine, and moss.',
        images: ['https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=640&h=640&fit=crop'],
        category: categories[2]._id,
        brand: brands[4]._id,
        price: 28500,
        sizes: [
          { size: '15ml', price: 8200, stock: 65, sku: 'LL-A13-15' },
          { size: '50ml', price: 19000, stock: 90, sku: 'LL-A13-50' },
          { size: '100ml', price: 28500, stock: 70, sku: 'LL-A13-100' },
        ],
        concentration: 'EDP',
        topNotes: ['Pear', 'Bergamot'],
        middleNotes: ['Jasmine Absolute', 'Ambroxan'],
        baseNotes: ['Moss', 'Musk', 'Cetalox'],
        longevity: 'Good',
        projection: 'Moderate',
        sillage: 'Moderate',
        season: 'All Seasons',
        occasion: 'Everyday',
        gender: 'unisex',
        tags: ['minimalist', 'musk', 'unisex', 'modern', 'cult'],
        isFeatured: true,
        isTrending: true,
        isBestSeller: false,
        isNewArrival: false,
        isLimitedEdition: false,
        isVisible: true,
        stock: 70,
        lowStockThreshold: 10,
      },
      {
        name: 'English Pear & Freesia',
        description: 'Jo Malone\'s beloved classic captures the essence of autumn in a bottle. The crisp, juicy scent of freshly picked pears is wrapped in the delicate floralcy of freesia, with a base of amber, patchouli, and woods.',
        shortDescription: 'A beloved classic capturing the crisp, juicy essence of autumn pears and freesia.',
        images: ['https://images.unsplash.com/photo-1600612253971-422e7f7faeb6?w=640&h=640&fit=crop'],
        category: categories[0]._id,
        brand: brands[5]._id,
        price: 14000,
        sizes: [
          { size: '30ml', price: 6800, stock: 120, sku: 'JM-EP-30' },
          { size: '100ml', price: 14000, stock: 180, sku: 'JM-EP-100' },
        ],
        concentration: 'Cologne',
        topNotes: ['Pear', 'Melon', 'Bergamot'],
        middleNotes: ['Freesia', 'Rose', 'Rhubarb'],
        baseNotes: ['Amber', 'Patchouli', 'Woodsy Notes', 'Musk'],
        longevity: 'Moderate',
        projection: 'Moderate',
        sillage: 'Moderate',
        season: 'Fall',
        occasion: 'Casual',
        gender: 'female',
        tags: ['fruity', 'floral', 'feminine', 'classic', 'layering'],
        isFeatured: false,
        isTrending: false,
        isBestSeller: true,
        isNewArrival: false,
        isLimitedEdition: false,
        isVisible: true,
        stock: 180,
        lowStockThreshold: 20,
      },
      {
        name: 'Bal d\'Afrique',
        description: 'An energetic, vibrant fragrance inspired by the cultural avant-garde of 1920s Paris and its fascination with African art. Citrusy top notes of bergamot and lemon give way to a heart of violet and jasmine, resting on a warm base of cedar and musk.',
        shortDescription: 'A vibrant blend of citrus, violet, jasmine, and warm cedar inspired by 1920s Paris.',
        images: ['https://images.unsplash.com/photo-1551103782-8ab07afd45c1?w=640&h=640&fit=crop'],
        category: categories[4]._id,
        brand: brands[6]._id,
        price: 27000,
        sizes: [
          { size: '50ml', price: 18500, stock: 50, sku: 'BY-BA-50' },
          { size: '100ml', price: 27000, stock: 80, sku: 'BY-BA-100' },
        ],
        concentration: 'EDP',
        topNotes: ['Bergamot', 'Lemon', 'African Marigold', 'Buchu'],
        middleNotes: ['Violet', 'Jasmine', 'Cyclamen', 'Clary Sage'],
        baseNotes: ['Cedar', 'Musk', 'Vetiver', 'Amber'],
        longevity: 'Good',
        projection: 'Moderate',
        sillage: 'Good',
        season: 'Summer',
        occasion: 'Evening',
        gender: 'unisex',
        tags: ['citrus', 'floral', 'vibrant', 'unisex', 'sophisticated'],
        isFeatured: false,
        isTrending: false,
        isBestSeller: false,
        isNewArrival: false,
        isLimitedEdition: false,
        isVisible: true,
        stock: 80,
        lowStockThreshold: 10,
      },
      {
        name: 'Beach Walk',
        description: 'A nostalgic fragrance that captures the warm, carefree feeling of a day at the beach. Creamy coconut, bergamot, and lemon blend with solar notes and musk to recreate the scent of sun-kissed skin and salty air.',
        shortDescription: 'A nostalgic beach scent with coconut, bergamot, and warm solar notes.',
        images: ['https://images.unsplash.com/photo-1522512115668-c09775d6f424?w=640&h=640&fit=crop'],
        category: categories[3]._id,
        brand: brands[7]._id,
        price: 15000,
        sizes: [
          { size: '30ml', price: 7800, stock: 90, sku: 'MM-BW-30' },
          { size: '100ml', price: 15000, stock: 130, sku: 'MM-BW-100' },
        ],
        concentration: 'EDT',
        topNotes: ['Bergamot', 'Lemon', 'Pink Pepper'],
        middleNotes: ['Coconut', 'Sea Spray', 'Solar Notes', 'Ylang-Ylang'],
        baseNotes: ['Musk', 'Cedar', 'Benzoin'],
        longevity: 'Moderate',
        projection: 'Moderate',
        sillage: 'Good',
        season: 'Summer',
        occasion: 'Casual',
        gender: 'female',
        tags: ['summer', 'coconut', 'beach', 'nostalgic', 'fresh'],
        isFeatured: false,
        isTrending: false,
        isBestSeller: false,
        isNewArrival: false,
        isLimitedEdition: false,
        isVisible: true,
        stock: 130,
        lowStockThreshold: 15,
      },
      {
        name: 'Good Girl Gone Bad',
        description: 'A seductive, intoxicating fragrance that embodies duality - innocence and temptation. The opening of neroli and osmanthus gives way to a heart of rose, jasmine, and tuberose, with a deep base of amber, cedar, and musk.',
        shortDescription: 'A seductive duality of neroli, tuberose, and amber - innocence meets temptation.',
        images: ['https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=640&h=640&fit=crop'],
        category: categories[0]._id,
        brand: brands[8]._id,
        price: 28000,
        sizes: [
          { size: '50ml', price: 18500, stock: 35, sku: 'KL-GG-50' },
          { size: '100ml', price: 28000, stock: 60, sku: 'KL-GG-100' },
        ],
        concentration: 'EDP',
        topNotes: ['Neroli', 'Osmanthus', 'Bergamot'],
        middleNotes: ['Rose', 'Jasmine', 'Tuberose', 'Orange Blossom'],
        baseNotes: ['Amber', 'Cedar', 'Musk', 'Vanilla'],
        longevity: 'Excellent',
        projection: 'Very Good',
        sillage: 'Excellent',
        season: 'Spring',
        occasion: 'Romantic',
        gender: 'female',
        tags: ['floral', 'sensual', 'feminine', 'luxury', 'romantic'],
        isFeatured: false,
        isTrending: true,
        isBestSeller: true,
        isNewArrival: false,
        isLimitedEdition: false,
        isVisible: true,
        stock: 60,
        lowStockThreshold: 10,
      },
      {
        name: 'Eau Rose Eau de Parfum',
        description: 'An exquisite, modern interpretation of the rose. Diptyque captures the essence of a blooming rose garden with a blend of Damask and Centifolia roses, enhanced with artichoke, lychee, and a woody base of cedar and musk.',
        shortDescription: 'A modern rose fragrance blending Damask and Centifolia roses with lychee and cedar.',
        images: ['https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=640&h=640&fit=crop'],
        category: categories[0]._id,
        brand: brands[9]._id,
        price: 18500,
        sizes: [
          { size: '50ml', price: 13500, stock: 60, sku: 'DP-ER-50' },
          { size: '100ml', price: 18500, stock: 90, sku: 'DP-ER-100' },
        ],
        concentration: 'EDP',
        topNotes: ['Lychee', 'Artichoke', 'Bergamot'],
        middleNotes: ['Damask Rose', 'Centifolia Rose'],
        baseNotes: ['Cedar', 'Musk', 'White Woods'],
        longevity: 'Good',
        projection: 'Moderate',
        sillage: 'Good',
        season: 'Spring',
        occasion: 'Everyday',
        gender: 'female',
        tags: ['rose', 'floral', 'feminine', 'elegant', 'natural'],
        isFeatured: false,
        isTrending: false,
        isBestSeller: false,
        isNewArrival: false,
        isLimitedEdition: false,
        isVisible: true,
        stock: 90,
        lowStockThreshold: 10,
      },
      {
        name: 'Ombre Leather Eau de Parfum',
        description: 'A bold, sensual leather fragrance from Tom Ford. This striking scent opens with cardamom and jasmine before revealing its heart of rich, supple leather. The base of vetiver, amber, and moss creates a powerful, unforgettable trail.',
        shortDescription: 'A bold leather fragrance with cardamom, jasmine, and rich leather accord.',
        images: ['https://images.unsplash.com/photo-1541643600914-78b084683601?w=640&h=640&fit=crop'],
        category: categories[2]._id,
        brand: brands[0]._id,
        price: 20500,
        sizes: [
          { size: '30ml', price: 10500, stock: 55, sku: 'TF-OL-30' },
          { size: '50ml', price: 16500, stock: 80, sku: 'TF-OL-50' },
          { size: '100ml', price: 20500, stock: 100, sku: 'TF-OL-100' },
        ],
        concentration: 'EDP',
        topNotes: ['Cardamom', 'Jasmine', 'Violet'],
        middleNotes: ['Leather', 'White Flowers'],
        baseNotes: ['Vetiver', 'Amber', 'Moss', 'Patchouli'],
        longevity: 'Very Good',
        projection: 'Excellent',
        sillage: 'Excellent',
        season: 'Fall',
        occasion: 'Evening',
        gender: 'unisex',
        tags: ['leather', 'bold', 'sensual', 'unisex', 'luxury'],
        isFeatured: true,
        isTrending: true,
        isBestSeller: false,
        isNewArrival: false,
        isLimitedEdition: false,
        isVisible: true,
        stock: 100,
        lowStockThreshold: 10,
      },
      {
        name: 'Acqua di Gio Profondo',
        description: 'An intense, deep interpretation of the classic Acqua di Gio. Profondo plunges into the depths of the ocean with notes of solar accord, cypress, and bergamot. A powerful aquatic fragrance that captures the mystery of the deep sea.',
        shortDescription: 'A deep, intense aquatic fragrance with solar accord, cypress, and bergamot.',
        images: ['https://images.unsplash.com/photo-1587017539504-67cfbddac569?w=640&h=640&fit=crop'],
        category: categories[6]._id,
        brand: brands[1]._id,
        price: 13000,
        sizes: [
          { size: '50ml', price: 8800, stock: 100, sku: 'AG-ADP-50' },
          { size: '100ml', price: 13000, stock: 160, sku: 'AG-ADP-100' },
        ],
        concentration: 'EDP',
        topNotes: ['Bergamot', 'Solar Accord', 'Green Mandarin'],
        middleNotes: ['Cypress', 'Rosemary', 'Lavender'],
        baseNotes: ['Musk', 'Amber', 'Patchouli'],
        longevity: 'Very Good',
        projection: 'Very Good',
        sillage: 'Good',
        season: 'Summer',
        occasion: 'Casual',
        gender: 'male',
        tags: ['aquatic', 'fresh', 'summer', 'masculine', 'classic'],
        isFeatured: false,
        isTrending: false,
        isBestSeller: true,
        isNewArrival: false,
        isLimitedEdition: false,
        isVisible: true,
        stock: 160,
        lowStockThreshold: 15,
      },
      {
        name: 'Coco Mademoiselle Eau de Parfum',
        description: 'An intensely modern, sparkling fragrance for the confident woman. Fresh orange and bergamot open to a heart of jasmine and rose, with a sensual base of patchouli, vetiver, and vanilla. An icon of modern femininity.',
        shortDescription: 'A sparkling modern icon with orange, jasmine, rose, and warm patchouli.',
        images: ['https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=640&h=640&fit=crop'],
        category: categories[0]._id,
        brand: brands[2]._id,
        price: 16000,
        sizes: [
          { size: '35ml', price: 8800, stock: 70, sku: 'CH-CM-35' },
          { size: '50ml', price: 12500, stock: 100, sku: 'CH-CM-50' },
          { size: '100ml', price: 16000, stock: 120, sku: 'CH-CM-100' },
        ],
        concentration: 'EDP',
        topNotes: ['Orange', 'Bergamot', 'Grapefruit'],
        middleNotes: ['Jasmine', 'Rose', 'Lychee'],
        baseNotes: ['Patchouli', 'Vetiver', 'Vanilla', 'Musk'],
        longevity: 'Very Good',
        projection: 'Good',
        sillage: 'Very Good',
        season: 'All Seasons',
        occasion: 'Special Occasion',
        gender: 'female',
        tags: ['floral', 'modern', 'iconic', 'feminine', 'classic'],
        isFeatured: false,
        isTrending: true,
        isBestSeller: true,
        isNewArrival: false,
        isLimitedEdition: false,
        isVisible: true,
        stock: 120,
        lowStockThreshold: 15,
      },
      {
        name: 'Silver Mountain Water',
        description: 'A crisp, refreshing fragrance that evokes the purity of alpine spring water and mountain air. Creed\'s masterpiece combines blackcurrant, bergamot, and green tea with a base of sandalwood and ambergris for a unique, invigorating scent.',
        shortDescription: 'A crisp alpine fragrance with blackcurrant, green tea, and sandalwood.',
        images: ['https://images.unsplash.com/photo-1563170351-be82bc888aa4?w=640&h=640&fit=crop'],
        category: categories[3]._id,
        brand: brands[3]._id,
        price: 41500,
        sizes: [
          { size: '50ml', price: 28500, stock: 20, sku: 'CR-SMW-50' },
          { size: '100ml', price: 41500, stock: 35, sku: 'CR-SMW-100' },
        ],
        concentration: 'EDP',
        topNotes: ['Blackcurrant', 'Bergamot', 'Galbanum'],
        middleNotes: ['Green Tea', 'Mountain Air Accord'],
        baseNotes: ['Sandalwood', 'Ambergris', 'White Musk'],
        longevity: 'Good',
        projection: 'Moderate',
        sillage: 'Good',
        season: 'Spring',
        occasion: 'Office',
        gender: 'unisex',
        tags: ['fresh', 'clean', 'premium', 'unisex', 'refined'],
        isFeatured: false,
        isTrending: true,
        isBestSeller: false,
        isNewArrival: false,
        isLimitedEdition: false,
        isVisible: true,
        stock: 35,
        lowStockThreshold: 5,
      },
      {
        name: 'By the Fireplace',
        description: 'A comforting, warm fragrance that recreates the cozy feeling of sitting by a crackling fire on a cold winter night. Smoky guaiac wood and clove oil blend with sweet chestnut accord and vanilla for an irresistibly cozy scent.',
        shortDescription: 'A warm, cozy fragrance of smoky wood, chestnut, and vanilla by the fire.',
        images: ['https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=640&h=640&fit=crop'],
        category: categories[1]._id,
        brand: brands[7]._id,
        price: 15000,
        sizes: [
          { size: '30ml', price: 7800, stock: 85, sku: 'MM-BF-30' },
          { size: '100ml', price: 15000, stock: 120, sku: 'MM-BF-100' },
        ],
        concentration: 'EDT',
        topNotes: ['Clove Oil', 'Pink Pepper', 'Orange Blossom'],
        middleNotes: ['Chestnut Accord', 'Guaiac Wood', 'Cedar'],
        baseNotes: ['Vanilla', 'Benzoin', 'Peru Balsam'],
        longevity: 'Good',
        projection: 'Moderate',
        sillage: 'Good',
        season: 'Winter',
        occasion: 'Everyday',
        gender: 'unisex',
        tags: ['warm', 'smoky', 'cozy', 'winter', 'gourmand'],
        isFeatured: true,
        isTrending: true,
        isBestSeller: true,
        isNewArrival: false,
        isLimitedEdition: false,
        isVisible: true,
        stock: 120,
        lowStockThreshold: 10,
      },
      {
        name: 'Angels\' Share',
        description: 'An intoxicating, warm fragrance inspired by the whisky-making process where angels take their share as the liquid evaporates. Notes of cognac, cinnamon, and tonka bean create a rich, boozy scent with unparalleled warmth and sophistication.',
        shortDescription: 'A rich, boozy blend of cognac, cinnamon, and tonka bean inspired by whisky-making.',
        images: ['https://images.unsplash.com/photo-1600612253971-422e7f7faeb6?w=640&h=640&fit=crop'],
        category: categories[5]._id,
        brand: brands[8]._id,
        price: 25000,
        sizes: [
          { size: '50ml', price: 17000, stock: 40, sku: 'KL-AS-50' },
          { size: '100ml', price: 25000, stock: 65, sku: 'KL-AS-100' },
        ],
        concentration: 'EDP',
        topNotes: ['Cognac', 'Cinnamon', 'Nutmeg'],
        middleNotes: ['Tonka Bean', 'Tobacco', 'Oak'],
        baseNotes: ['Vanilla', 'Sandalwood', 'Amber'],
        longevity: 'Excellent',
        projection: 'Very Good',
        sillage: 'Excellent',
        season: 'Winter',
        occasion: 'Evening',
        gender: 'unisex',
        tags: ['boozy', 'warm', 'gourmand', 'luxury', 'winter'],
        isFeatured: true,
        isTrending: true,
        isBestSeller: true,
        isNewArrival: false,
        isLimitedEdition: false,
        isVisible: true,
        stock: 65,
        lowStockThreshold: 10,
      },
      {
        name: 'Eau des Sens',
        description: 'A vibrant, aromatic cologne that captures the essence of the Mediterranean maquis. The bitter, radiant scent of orange tree in all its forms - leaves, flowers, and fruit - blended with angelica, juniper, and patchouli for a refreshing, sophisticated scent.',
        shortDescription: 'A vibrant Mediterranean cologne celebrating the orange tree in all its forms.',
        images: ['https://images.unsplash.com/photo-1551103782-8ab07afd45c1?w=640&h=640&fit=crop'],
        category: categories[4]._id,
        brand: brands[9]._id,
        price: 16000,
        sizes: [
          { size: '50ml', price: 11000, stock: 50, sku: 'DP-EDS-50' },
          { size: '100ml', price: 16000, stock: 80, sku: 'DP-EDS-100' },
        ],
        concentration: 'EDT',
        topNotes: ['Orange Blossom', 'Bitter Orange', 'Angelica'],
        middleNotes: ['Juniper', 'Lemon Leaf', 'Lavender'],
        baseNotes: ['Patchouli', 'Cedar', 'Pine'],
        longevity: 'Moderate',
        projection: 'Moderate',
        sillage: 'Good',
        season: 'Summer',
        occasion: 'Casual',
        gender: 'unisex',
        tags: ['citrus', 'fresh', 'mediterranean', 'unisex', 'natural'],
        isFeatured: false,
        isTrending: false,
        isBestSeller: false,
        isNewArrival: false,
        isLimitedEdition: false,
        isVisible: true,
        stock: 80,
        lowStockThreshold: 10,
      },
      {
        name: 'Tuscan Leather',
        description: 'A powerful, luxurious leather fragrance from Tom Ford\'s Private Blend. This bold composition opens with raspberry and saffron before revealing its heart of pure Tuscan leather. The base of amber and suede creates an unforgettable, opulent trail.',
        shortDescription: 'A powerful leather fragrance with raspberry, saffron, and Tuscan leather.',
        images: ['https://images.unsplash.com/photo-1522512115668-c09775d6f424?w=640&h=640&fit=crop'],
        category: categories[2]._id,
        brand: brands[0]._id,
        price: 31000,
        sizes: [
          { size: '50ml', price: 21000, stock: 30, sku: 'TF-TL-50' },
          { size: '100ml', price: 31000, stock: 55, sku: 'TF-TL-100' },
        ],
        concentration: 'EDP',
        topNotes: ['Raspberry', 'Saffron', 'Thyme'],
        middleNotes: ['Leather', 'Jasmine', 'White Suede'],
        baseNotes: ['Amber', 'Woodsy Notes', 'Musk'],
        longevity: 'Excellent',
        projection: 'Excellent',
        sillage: 'Excellent',
        season: 'Fall',
        occasion: 'Formal',
        gender: 'male',
        tags: ['leather', 'bold', 'luxury', 'masculine', 'private-blend'],
        isFeatured: true,
        isTrending: false,
        isBestSeller: true,
        isNewArrival: false,
        isLimitedEdition: false,
        isVisible: true,
        stock: 55,
        lowStockThreshold: 10,
      },
      {
        name: 'Fahrenheit Eau de Toilette',
        description: 'A revolutionary, groundbreaking fragrance that defied conventions. An iconic blend of violet, leather, and nutmeg with an unmistakable gasoline-like note that creates a uniquely warm, sensual, and utterly distinctive scent.',
        shortDescription: 'A revolutionary icon with violet, leather, and its signature gasoline note.',
        images: ['https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=640&h=640&fit=crop'],
        category: categories[2]._id,
        brand: brands[1]._id,
        price: 11500,
        sizes: [
          { size: '50ml', price: 7800, stock: 75, sku: 'DR-FH-50' },
          { size: '100ml', price: 11500, stock: 110, sku: 'DR-FH-100' },
        ],
        concentration: 'EDT',
        topNotes: ['Violet', 'Nutmeg', 'Hawthorn', 'Lavender'],
        middleNotes: ['Leather', 'Carnation', 'Honey', 'Jasmine'],
        baseNotes: ['Woody Notes', 'Musk', 'Vanilla', 'Amber'],
        longevity: 'Good',
        projection: 'Very Good',
        sillage: 'Very Good',
        season: 'Fall',
        occasion: 'Everyday',
        gender: 'male',
        tags: ['iconic', 'violet', 'leather', 'masculine', 'unique'],
        isFeatured: false,
        isTrending: false,
        isBestSeller: true,
        isNewArrival: false,
        isLimitedEdition: false,
        isVisible: true,
        stock: 110,
        lowStockThreshold: 15,
      },
      {
        name: 'La Vie Est Belle Eau de Parfum',
        description: 'The ultimate fragrance of happiness and joy. An addictive, sweet floral gourmand with a sparkling top of blackcurrant and pear, blooming into iris and jasmine, resting on a warm, delicious base of praline, vanilla, and patchouli.',
        shortDescription: 'An addictive sweet floral gourmand with iris, praline, and vanilla.',
        images: ['https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?w=640&h=640&fit=crop'],
        category: categories[5]._id,
        brand: brands[1]._id,
        price: 12000,
        sizes: [
          { size: '30ml', price: 6200, stock: 90, sku: 'LV-LV-30' },
          { size: '50ml', price: 9200, stock: 130, sku: 'LV-LV-50' },
          { size: '100ml', price: 12000, stock: 170, sku: 'LV-LV-100' },
        ],
        concentration: 'EDP',
        topNotes: ['Blackcurrant', 'Pear', 'Bergamot'],
        middleNotes: ['Iris', 'Jasmine', 'Orange Blossom'],
        baseNotes: ['Praline', 'Vanilla', 'Patchouli', 'Tonka Bean'],
        longevity: 'Very Good',
        projection: 'Very Good',
        sillage: 'Good',
        season: 'Spring',
        occasion: 'Everyday',
        gender: 'female',
        tags: ['gourmand', 'sweet', 'feminine', 'popular', 'joyful'],
        isFeatured: false,
        isTrending: false,
        isBestSeller: true,
        isNewArrival: false,
        isLimitedEdition: false,
        isVisible: true,
        stock: 170,
        lowStockThreshold: 20,
      },
      {
        name: 'Tam Dao Eau de Parfum',
        description: 'A meditative, serene fragrance centered on the precious sandalwood from Mysore. Diptyque\'s masterpiece is a pure, contemplative woody scent with notes of rosewood, cypress, and cedar that creates an atmosphere of calm and tranquility.',
        shortDescription: 'A meditative, serene sandalwood fragrance with rosewood and cedar.',
        images: ['https://images.unsplash.com/photo-1541643600914-78b084683601?w=640&h=640&fit=crop'],
        category: categories[2]._id,
        brand: brands[9]._id,
        price: 20000,
        sizes: [
          { size: '50ml', price: 14000, stock: 45, sku: 'DP-TD-50' },
          { size: '100ml', price: 20000, stock: 70, sku: 'DP-TD-100' },
        ],
        concentration: 'EDP',
        topNotes: ['Rosewood', 'Cypress', 'Bergamot'],
        middleNotes: ['Sandalwood', 'Cedar', 'Spices'],
        baseNotes: ['White Musk', 'Amber', 'Coconut'],
        longevity: 'Good',
        projection: 'Moderate',
        sillage: 'Good',
        season: 'All Seasons',
        occasion: 'Office',
        gender: 'unisex',
        tags: ['sandalwood', 'woody', 'meditative', 'unisex', 'minimalist'],
        isFeatured: false,
        isTrending: false,
        isBestSeller: false,
        isNewArrival: false,
        isLimitedEdition: false,
        isVisible: true,
        stock: 70,
        lowStockThreshold: 10,
      },
      {
        name: 'L\'Immensité Eau de Parfum',
        description: 'A vast, expansive fragrance that evokes endless horizons. Fresh, spicy, and woody - grapefruit and ginger open with startling clarity before a heart of lavender and sage leads to a base of vetiver, amber, and cedar.',
        shortDescription: 'A vast, expansive fragrance with grapefruit, ginger, lavender, and vetiver.',
        images: ['https://images.unsplash.com/photo-1587017539504-67cfbddac569?w=640&h=640&fit=crop'],
        category: categories[3]._id,
        brand: brands[0]._id,
        price: 18000,
        sizes: [
          { size: '50ml', price: 12000, stock: 50, sku: 'TF-LI-50' },
          { size: '100ml', price: 18000, stock: 80, sku: 'TF-LI-100' },
        ],
        concentration: 'EDP',
        topNotes: ['Grapefruit', 'Ginger', 'Rhubarb'],
        middleNotes: ['Lavender', 'Sage', 'Rosemary'],
        baseNotes: ['Vetiver', 'Amber', 'Cedar', 'Musk'],
        longevity: 'Very Good',
        projection: 'Good',
        sillage: 'Very Good',
        season: 'Summer',
        occasion: 'Everyday',
        gender: 'male',
        tags: ['fresh', 'spicy', 'masculine', 'versatile', 'modern'],
        isFeatured: false,
        isTrending: true,
        isBestSeller: false,
        isNewArrival: true,
        isLimitedEdition: false,
        isVisible: true,
        stock: 80,
        lowStockThreshold: 10,
      },
      {
        name: 'Flowerbomb Eau de Parfum',
        description: 'An explosive floral bouquet that is both intoxicating and elegant. Orchid, jasmine, and freesia blend with rose and patchouli to create a powerful, sensual floral that has become a modern classic.',
        shortDescription: 'An explosive floral bouquet of orchid, jasmine, rose, and patchouli.',
        images: ['https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=640&h=640&fit=crop'],
        category: categories[0]._id,
        brand: brands[8]._id,
        price: 23500,
        sizes: [
          { size: '50ml', price: 15500, stock: 55, sku: 'KL-FB-50' },
          { size: '100ml', price: 23500, stock: 85, sku: 'KL-FB-100' },
        ],
        concentration: 'EDP',
        topNotes: ['Bergamot', 'Tea', 'Osmanthus'],
        middleNotes: ['Orchid', 'Jasmine', 'Freesia', 'Rose'],
        baseNotes: ['Patchouli', 'Musk', 'Vanilla', 'Amber'],
        longevity: 'Very Good',
        projection: 'Very Good',
        sillage: 'Excellent',
        season: 'Spring',
        occasion: 'Evening',
        gender: 'female',
        tags: ['floral', 'explosive', 'feminine', 'luxury', 'iconic'],
        isFeatured: false,
        isTrending: false,
        isBestSeller: true,
        isNewArrival: false,
        isLimitedEdition: false,
        isVisible: true,
        stock: 85,
        lowStockThreshold: 10,
      },
      {
        name: 'Santal Cardamol Eau de Parfum',
        description: 'A warm, spicy interpretation of sandalwood from Jo Malone. The creamy smoothness of sandalwood is elevated by the aromatic warmth of cardamom, with hints of cedar and tonka adding depth and sensuality.',
        shortDescription: 'A warm, spicy sandalwood elevated by cardamom, cedar, and tonka.',
        images: ['https://images.unsplash.com/photo-1563170351-be82bc888aa4?w=640&h=640&fit=crop'],
        category: categories[2]._id,
        brand: brands[5]._id,
        price: 15500,
        sizes: [
          { size: '30ml', price: 7500, stock: 70, sku: 'JM-SC-30' },
          { size: '100ml', price: 15500, stock: 100, sku: 'JM-SC-100' },
        ],
        concentration: 'Cologne',
        topNotes: ['Cardamom', 'Juniper'],
        middleNotes: ['Sandalwood', 'Cedar', 'Lavender'],
        baseNotes: ['Tonka Bean', 'Musk', 'Vanilla'],
        longevity: 'Moderate',
        projection: 'Moderate',
        sillage: 'Good',
        season: 'Fall',
        occasion: 'Everyday',
        gender: 'unisex',
        tags: ['sandalwood', 'spicy', 'warm', 'unisex', 'layering'],
        isFeatured: false,
        isTrending: false,
        isBestSeller: false,
        isNewArrival: true,
        isLimitedEdition: false,
        isVisible: true,
        stock: 100,
        lowStockThreshold: 10,
      },
    ]);

    console.log('Products created...');

    // Create Coupons
    const coupons = await Coupon.create([
      { code: 'WELCOME20', type: 'percentage', value: 20, minOrder: 100, maxDiscount: 50, usageLimit: 100, usageCount: 0, isActive: true, expiresAt: new Date('2026-12-31') },
      { code: 'LUXURY50', type: 'fixed', value: 50, minOrder: 250, usageLimit: 50, usageCount: 0, isActive: true, expiresAt: new Date('2026-12-31') },
      { code: 'SUMMER15', type: 'percentage', value: 15, minOrder: 150, maxDiscount: 40, usageLimit: 200, usageCount: 0, isActive: true, expiresAt: new Date('2026-09-30') },
      { code: 'VIP30', type: 'percentage', value: 30, minOrder: 300, maxDiscount: 100, usageLimit: 25, usageCount: 0, isActive: true, expiresAt: new Date('2026-12-31') },
      { code: 'FREE_SHIPPING', type: 'fixed', value: 9.99, minOrder: 75, usageLimit: 500, usageCount: 0, isActive: true, expiresAt: new Date('2026-12-31') },
      { code: 'GIFT25', type: 'fixed', value: 25, minOrder: 125, usageLimit: 100, usageCount: 0, isActive: true, expiresAt: new Date('2026-12-31') },
    ]);

    console.log('Coupons created...');

    // Create Reviews
    const reviews = await Review.create([
      { user: users[2]._id, product: products[0]._id, rating: 5, title: 'Absolutely Captivating', comment: 'This is hands down the most sophisticated fragrance I own. The black truffle opening is unique and the dry down is divine. Lasts over 8 hours on my skin.', isApproved: true },
      { user: users[3]._id, product: products[0]._id, rating: 4, title: 'Bold and Beautiful', comment: 'A truly bold scent that commands attention. Not for the faint of heart but if you want to make a statement, this is it.', isApproved: true },
      { user: users[2]._id, product: products[1]._id, rating: 5, title: 'The Best Sauvage Version', comment: 'Elixir is on another level compared to the original. The concentration is incredible and it projects like a beast. One spray is enough for the whole day.', isApproved: true },
      { user: users[4]._id, product: products[2]._id, rating: 5, title: 'Timeless Elegance', comment: 'There is a reason this fragrance has been a legend for over a century. It is elegant, sophisticated, and unforgettable.', isApproved: true },
      { user: users[3]._id, product: products[3]._id, rating: 5, title: 'Best Fragrance Ever Made', comment: 'Worth every penny. The pineapple opening is legendary and the birch gives it such a unique character. Compliments everywhere I go.', isApproved: true },
      { user: users[2]._id, product: products[4]._id, rating: 5, title: 'Cult Classic for a Reason', comment: 'Santal 33 is unlike anything else. It smells different on everyone and has this addictive quality that makes people ask what you are wearing.', isApproved: true },
      { user: users[4]._id, product: products[5]._id, rating: 4, title: 'Perfect Summer Scent', comment: 'Light, fresh, and incredibly evocative. It smells like a walk on a breezy beach. Longevity could be better but the scent itself is perfection.', isApproved: true },
      { user: users[3]._id, product: products[6]._id, rating: 5, title: 'Mystical and Beautiful', comment: 'Gypsy Water is pure magic. It has this ethereal quality that is both grounding and uplifting. The juniper and vanilla combination is genius.', isApproved: true },
      { user: users[2]._id, product: products[7]._id, rating: 5, title: 'Best Club Scent', comment: 'Jazz Club perfectly captures a mood. The rum and tobacco are so well blended. Perfect for date nights and evenings out.', isApproved: true },
      { user: users[4]._id, product: products[8]._id, rating: 5, title: 'Sweet Seduction', comment: 'This is the most romantic scent I have ever tried. The marshmallow note is gorgeous without being childish. Longevity is incredible.', isApproved: true },
      { user: users[3]._id, product: products[9]._id, rating: 4, title: 'Beautiful Natural Scent', comment: 'Philosykos is the most realistic fig scent I have ever encountered. It is green, milky, and absolutely transports you to the Mediterranean.', isApproved: true },
      { user: users[2]._id, product: products[10]._id, rating: 5, title: 'Winter Essential', comment: 'Tobacco Vanille is the ultimate cold weather fragrance. It is warm, sweet, and has incredible performance. Worth every penny.', isApproved: true },
      { user: users[4]._id, product: products[11]._id, rating: 5, title: 'The Perfect Floral', comment: 'J\'adore is everything a feminine fragrance should be. Beautiful, elegant, and long-lasting. A staple in any collection.', isApproved: true },
      { user: users[3]._id, product: products[12]._id, rating: 5, title: 'Office King', comment: 'Bleu de Chanel is the most versatile fragrance I own. Works for the office, dates, and everything in between. Class in a bottle.', isApproved: true },
      { user: users[2]._id, product: products[13]._id, rating: 5, title: 'Green Perfection', comment: 'Green Irish Tweed is a masterpiece of freshness. The violet leaf and sandalwood combination is pure class. A must-have for any collection.', isApproved: true },
    ]);

    console.log('Reviews created...');

    // Create Orders
    const orderItems1 = [
      { product: products[0]._id, name: products[0].name, image: products[0].images[0], size: '50ml', quantity: 1, price: 15500 },
      { product: products[3]._id, name: products[3].name, image: products[3].images[0], size: '100ml', quantity: 1, price: 43500 },
    ];

    const orderItems2 = [
      { product: products[4]._id, name: products[4].name, image: products[4].images[0], size: '50ml', quantity: 2, price: 19800 },
    ];

    const orderItems3 = [
      { product: products[7]._id, name: products[7].name, image: products[7].images[0], size: '100ml', quantity: 1, price: 15000 },
      { product: products[22]._id, name: products[22].name, image: products[22].images[0], size: '100ml', quantity: 1, price: 15000 },
    ];

    const orderItems4 = [
      { product: products[1]._id, name: products[1].name, image: products[1].images[0], size: '60ml', quantity: 1, price: 14500 },
    ];

    const orderItems5 = [
      { product: products[2]._id, name: products[2].name, image: products[2].images[0], size: '50ml', quantity: 1, price: 13500 },
      { product: products[11]._id, name: products[11].name, image: products[11].images[0], size: '50ml', quantity: 1, price: 10800 },
    ];

    const address1 = { name: 'Sarah Khan', phone: '+92-300-3333333', street: '25 F-7 Markaz', city: 'Islamabad', state: 'ICT', zip: '44000', country: 'Pakistan' };
    const address2 = { name: 'Ahmed Ali', phone: '+92-300-4444444', street: '55 Gulberg III', city: 'Lahore', state: 'Punjab', zip: '54660', country: 'Pakistan' };
    const address3 = { name: 'Fatima Zaidi', phone: '+92-300-5555555', street: '8 University Road', city: 'Karachi', state: 'Sindh', zip: '75270', country: 'Pakistan' };

    await Order.create([
      {
        user: users[2]._id, orderItems: orderItems1,
        shippingAddress: address1, billingAddress: address1,
        paymentMethod: 'credit_card', paymentStatus: 'completed',
        subtotal: 59000, tax: 5900, shippingCost: 0, discount: 5900, total: 59000,
        status: 'delivered', isPaid: true, paidAt: new Date('2026-01-15'), isDelivered: true, deliveredAt: new Date('2026-01-20'),
        statusHistory: [
          { status: 'pending', date: new Date('2026-01-14') },
          { status: 'confirmed', date: new Date('2026-01-14') },
          { status: 'packed', date: new Date('2026-01-15') },
          { status: 'shipped', date: new Date('2026-01-16') },
          { status: 'delivering', date: new Date('2026-01-18') },
          { status: 'delivered', date: new Date('2026-01-20') },
        ],
        trackingNumber: '1Z999AA10123456784',
      },
      {
        user: users[3]._id, orderItems: orderItems2,
        shippingAddress: address2, billingAddress: address2,
        paymentMethod: 'paypal', paymentStatus: 'completed',
        subtotal: 39600, tax: 3960, shippingCost: 999, discount: 0, total: 44559,
        status: 'shipped', isPaid: true, paidAt: new Date('2026-02-01'), isDelivered: false,
        statusHistory: [
          { status: 'pending', date: new Date('2026-01-30') },
          { status: 'confirmed', date: new Date('2026-01-31') },
          { status: 'packed', date: new Date('2026-02-01') },
          { status: 'shipped', date: new Date('2026-02-02') },
        ],
        trackingNumber: '1Z999AA10123456785',
      },
      {
        user: users[4]._id, orderItems: orderItems3,
        shippingAddress: address3, billingAddress: address3,
        paymentMethod: 'credit_card', paymentStatus: 'completed',
        subtotal: 30000, tax: 3000, shippingCost: 0, discount: 30, total: 30000,
        status: 'confirmed', isPaid: true, paidAt: new Date('2026-03-10'), isDelivered: false,
        statusHistory: [
          { status: 'pending', date: new Date('2026-03-10') },
          { status: 'confirmed', date: new Date('2026-03-10') },
        ],
      },
      {
        user: users[3]._id, orderItems: orderItems4,
        shippingAddress: address2, billingAddress: address2,
        paymentMethod: 'stripe', paymentStatus: 'pending',
        subtotal: 14500, tax: 1450, shippingCost: 999, discount: 0, total: 16949,
        status: 'pending', isPaid: false, isDelivered: false,
        statusHistory: [
          { status: 'pending', date: new Date('2026-03-15') },
        ],
      },
      {
        user: users[2]._id, orderItems: orderItems5,
        shippingAddress: address1, billingAddress: address1,
        paymentMethod: 'credit_card', paymentStatus: 'completed',
        subtotal: 24300, tax: 2430, shippingCost: 0, discount: 48.60, total: 21870,
        coupon: coupons[0]._id,
        status: 'delivered', isPaid: true, paidAt: new Date('2026-02-20'), isDelivered: true, deliveredAt: new Date('2026-02-25'),
        statusHistory: [
          { status: 'pending', date: new Date('2026-02-18') },
          { status: 'confirmed', date: new Date('2026-02-18') },
          { status: 'packed', date: new Date('2026-02-19') },
          { status: 'shipped', date: new Date('2026-02-20') },
          { status: 'delivering', date: new Date('2026-02-22') },
          { status: 'delivered', date: new Date('2026-02-25') },
        ],
        trackingNumber: '1Z999AA10123456786',
      },
    ]);

    console.log('Orders created...');

    // Create Banners
    await Banner.create([
      {
        title: 'Discover Your Signature Scent',
        subtitle: 'Explore Our Exclusive Collection',
        description: 'Handpicked fragrances from the world\'s most prestigious houses. Find the scent that defines you.',
        image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=1920&h=600&fit=crop',
        link: '/products',
        type: 'hero',
        isActive: true,
        order: 1,
      },
      {
        title: 'Summer Collection 2026',
        subtitle: 'Light & Breezy Fragrances',
        description: 'Embrace the warmth with our curated selection of summer-ready scents.',
        image: 'https://images.unsplash.com/photo-1587017539504-67cfbddac569?w=1920&h=600&fit=crop',
        link: '/collections/summer',
        type: 'hero',
        isActive: true,
        order: 2,
      },
      {
        title: 'Limited Edition Tom Ford',
        subtitle: 'Private Blend Collection',
        description: 'Experience the extraordinary. Exclusive fragrances for the connoisseur.',
        image: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=1920&h=600&fit=crop',
        link: '/products?brand=Tom+Ford',
        type: 'promotional',
        isActive: true,
        order: 1,
      },
    ]);

    console.log('Banners created...');

    // Create Settings
    await Settings.create({
      storeName: 'Scent Studio',
      currency: { code: 'PKR', symbol: 'Rs.', position: 'before', decimalPlaces: 0, thousandSeparator: ',', decimalSeparator: '.' },
      tax: { rate: 10, type: 'percentage', includedInPrice: false },
      shipping: { freeShippingThreshold: 15000, standardRate: 299, expressRate: 599, estimatedDelivery: '3-5 business days' },
      socialMedia: { facebook: 'https://facebook.com/luxuryperfume', instagram: 'https://instagram.com/luxuryperfume', twitter: 'https://twitter.com/luxuryperfume', pinterest: 'https://pinterest.com/luxuryperfume' },
      seo: { metaTitle: 'Scent Studio - Premium Fragrances in Pakistan', metaDescription: 'Discover the world of luxury fragrances at Scent Studio. Shop our curated collection of premium perfumes from Tom Ford, Dior, Chanel, Creed, and more.' },
    });

    console.log('Settings created...');

    const Blog = require('./models/Blog');
    const Collection = require('./models/Collection');
    const Newsletter = require('./models/Newsletter');

    await Promise.all([
      Blog.deleteMany({}),
      Collection.deleteMany({}),
      Newsletter.deleteMany({}),
    ]);

    const collections = await Collection.create([
      {
        name: 'Evening Ritual',
        description: 'Deep, enveloping compositions for after dark — woods, resins, and soft florals with lasting projection.',
        image: 'https://images.unsplash.com/photo-1595425970367-c77cafcb8c98?auto=format&fit=crop&w=1200&q=80',
        products: products.slice(0, 6).map((p: any) => p._id),
        isActive: true,
      },
      {
        name: 'Morning Light',
        description: 'Bright citrus, clean greens, and soft musks — scents that open the day with clarity.',
        image: 'https://images.unsplash.com/photo-1615634260167-c8cdede054de?auto=format&fit=crop&w=1200&q=80',
        products: products.slice(6, 12).map((p: any) => p._id),
        isActive: true,
      },
      {
        name: 'Signature Woods',
        description: 'Cedar, sandalwood, vetiver, and oud — a study in quiet strength and texture.',
        image: 'https://images.unsplash.com/photo-1588405748880-12d1d2a59db9?auto=format&fit=crop&w=1200&q=80',
        products: products.slice(12, 18).map((p: any) => p._id),
        isActive: true,
      },
      {
        name: 'Gift Edit',
        description: 'Ready-to-give selections and refined bottles for those who appreciate thoughtful scent.',
        image: 'https://images.unsplash.com/photo-1547887538-e3a2f32cbae5?auto=format&fit=crop&w=1200&q=80',
        products: products.filter((p: any) => p.isGiftSet || p.isFeatured).slice(0, 8).map((p: any) => p._id),
        isActive: true,
      },
    ]);

    console.log('Collections created...');

    await Blog.create([
      {
        title: 'How to Choose a Signature Fragrance',
        excerpt: 'A practical guide to finding a scent that feels like you — from notes and concentration to season and occasion.',
        content: '<p>Choosing a signature fragrance is less about trends and more about recognition. Begin with families you already enjoy — floral, woody, oriental, or fresh — then sample in real life, on skin, over several hours.</p><p>Consider concentration: Eau de Parfum often lasts longer for evening; Eau de Toilette can feel lighter for day. Layer with matching body care when possible, and store bottles away from heat and light.</p><p>At Scent Studio, we curate compositions that wear beautifully in Pakistan\'s climate — from soft daytime citrus to richer night woods.</p>',
        image: 'https://images.unsplash.com/photo-1595425970367-c77cafcb8c98?auto=format&fit=crop&w=1200&q=80',
        author: 'Scent Studio Editorial',
        tags: ['guides', 'signature', 'tips'],
        isPublished: true,
        publishedAt: new Date(),
      },
      {
        title: 'Understanding Fragrance Notes',
        excerpt: 'Top, heart, and base — how a perfume unfolds across time, and what each layer contributes.',
        content: '<p>Top notes are the first impression: citrus, herbs, light florals. They fade within minutes to an hour. Heart notes form the character of the scent — rose, jasmine, spices. Base notes linger longest: woods, amber, musk, vanilla.</p><p>Reading a pyramid helps you anticipate the dry-down. If you love the opening but not the base, keep sampling — longevity and preference rarely align on first spray alone.</p>',
        image: 'https://images.unsplash.com/photo-1615634260167-c8cdede054de?auto=format&fit=crop&w=1200&q=80',
        author: 'Scent Studio Editorial',
        tags: ['education', 'notes'],
        isPublished: true,
        publishedAt: new Date(),
      },
      {
        title: 'Layering Scents with Intention',
        excerpt: 'Subtle ways to combine fragrances without creating chaos on the skin.',
        content: '<p>Layering works best when one scent leads and another supports. Pair a simple musk or sandalwood with a brighter floral, or anchor a citrus with a soft amber. Apply the heavier composition first, then mist the lighter one.</p><p>Less is more — two products are usually enough. Allow each to settle before judging the result.</p>',
        image: 'https://images.unsplash.com/photo-1588405748880-12d1d2a59db9?auto=format&fit=crop&w=1200&q=80',
        author: 'Scent Studio Editorial',
        tags: ['layering', 'tips'],
        isPublished: true,
        publishedAt: new Date(),
      },
      {
        title: 'Caring for Your Perfume Collection',
        excerpt: 'Simple habits that protect composition, colour, and longevity of your bottles.',
        content: '<p>Keep fragrances upright, capped, and away from windows. Heat and UV light accelerate oxidation. Avoid storing in bathrooms where humidity swings. Decant bottles retain quality longer than opened ones — but an opened bottle stored well can remain beautiful for years.</p>',
        image: 'https://images.unsplash.com/photo-1547887538-e3a2f32cbae5?auto=format&fit=crop&w=1200&q=80',
        author: 'Scent Studio Editorial',
        tags: ['care', 'collection'],
        isPublished: true,
        publishedAt: new Date(),
      },
      {
        title: 'A Guide to Gift Sets',
        excerpt: 'How to choose a thoughtful perfume gift — size, concentration, and presentation.',
        content: '<p>Gift sets are ideal when you want a complete ritual: fragrance plus lotion or travel size. For first-time gifting, unisex woods and soft florals are safer than extreme niches. Include a handwritten note about why you chose the scent — that detail is remembered longer than the box.</p>',
        image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=1200&q=80',
        author: 'Scent Studio Editorial',
        tags: ['gifting', 'guides'],
        isPublished: true,
        publishedAt: new Date(),
      },
    ]);

    console.log('Blogs created...');

    await Newsletter.create([
      { email: 'sarah@example.com', isSubscribed: true },
      { email: 'james@example.com', isSubscribed: true },
      { email: 'collector@scentstudio.pk', isSubscribed: true },
    ]);

    console.log('Newsletter subscribers created...');

    console.log('\n✓ SEED DATA CREATED SUCCESSFULLY');
    console.log('─────────────────────────────────');
    console.log(`  Users:     ${users.length}`);
    console.log(`  Categories: ${categories.length}`);
    console.log(`  Brands:    ${brands.length}`);
    console.log(`  Products:  ${products.length}`);
    console.log(`  Coupons:   ${coupons.length}`);
    console.log(`  Reviews:   ${reviews.length}`);
    console.log('  Orders:    5');
    console.log('  Banners:   3');
    console.log(`  Collections: ${collections.length}`);
    console.log('  Blogs:     5');
    console.log('  Settings:  1');
    console.log('─────────────────────────────────');

    process.exit(0);
  } catch (error) {
    console.error('Seed failed:', error);
    process.exit(1);
  }
};

seed();

export {};

